version: '3.7'
 
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
        container_name: elasticsearch
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            - discovery.type=single-node
 
    kinaba:
        image: docker.elastic.co/kibana/kibana:7.13.4
        container_name: kibana
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch
